### ISSUE TITLE
System.Exception: Namespace and Folder name do not match. 

### ISSUE THREAD

**Issue by miozus** [Hallam9K/RedemptionAlpha#6]
It is my first time to use tmodloader and load the source of the  mod of RedempptionAlpha. 

Could you give me some advise? plz

![image](https://user-images.githubusercontent.com/35659194/190850307-0bcd929f-c1a4-48ac-af87-c4c89a0b696a.png)

```bash
# log
[17:28:10.627] [Main Thread/INFO] [tML]: Enabling Mod: RedemptionAlpha
[17:28:12.310] [.NET ThreadPool Worker/INFO] [tML]: Unloading: SubworldLibrary (Subworld Library) v2.0.1.2
[17:28:12.311] [.NET ThreadPool Worker/DEBUG] [tML]: Unloaded 0 hooks, 18 detours and 18 native detours from SubworldLibrary in Subworld Library
[17:28:12.328] [.NET ThreadPool Worker/INFO] [tML]: Unloading: ParticleLibrary ([c/9ebae2:Pa][c/dafaf4:rtic][c/9ebae2:le][c/e8a272:Li][c/fad3a0:bra][c/e8a272:ry]) v1.1.4.0
[17:28:12.330] [.NET ThreadPool Worker/DEBUG] [tML]: Unloaded 16 hooks, 16 detours and 15 native detours from ParticleLibrary in [c/9ebae2:Pa][c/dafaf4:rtic][c/9ebae2:le][c/e8a272:Li][c/fad3a0:bra][c/e8a272:ry]
[17:28:12.343] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Main::DrawDust() removed by ParticleLibrary
[17:28:12.362] [.NET ThreadPool Worker/INFO] [tML]: Unloading: CollisionLib (Impact Library) v2.1
[17:28:12.363] [.NET ThreadPool Worker/DEBUG] [tML]: Unloaded 1 hooks, 1 detours and 1 native detours from CollisionLib in Impact Library
[17:28:12.377] [.NET ThreadPool Worker/INFO] [tML]: Unloading: ModLoader (tModLoader) v2022.8.54.6
[17:28:13.198] [.NET ThreadPool Worker/WARN] [tML]: ParticleLibrary mod class still using memory. Some content references have probably not been cleared. Use a heap dump to figure out why.
[17:28:13.198] [.NET ThreadPool Worker/WARN] [tML]: RecipeBrowser AssemblyLoadContext still using memory. Some classes are being held by Terraria or another mod. Use a heap dump to figure out why.
[17:28:13.199] [.NET ThreadPool Worker/WARN] [tML]: CollisionLib mod class still using memory. Some content references have probably not been cleared. Use a heap dump to figure out why.
[17:28:13.199] [.NET ThreadPool Worker/WARN] [tML]: SubworldLibrary mod class still using memory. Some content references have probably not been cleared. Use a heap dump to figure out why.
[17:28:13.201] [.NET ThreadPool Worker/INFO] [tML]: Finding Mods...
[17:28:13.202] [.NET ThreadPool Worker/INFO] [tML]: Sandboxing: CollisionLib (Impact Library) v2.1
[17:28:13.207] [.NET ThreadPool Worker/INFO] [tML]: Sandboxing: ParticleLibrary ([c/9ebae2:Pa][c/dafaf4:rtic][c/9ebae2:le][c/e8a272:Li][c/fad3a0:bra][c/e8a272:ry]) v1.1.4.0
[17:28:13.212] [.NET ThreadPool Worker/INFO] [tML]: Sandboxing: SubworldLibrary (Subworld Library) v2.0.1.2
[17:28:13.217] [.NET ThreadPool Worker/INFO] [tML]: Sandboxing: RedemptionAlpha (Mod of Redemption) v0.8
[17:28:13.337] [.NET ThreadPool Worker/INFO] [tML]: Constructing Mods...
[17:28:13.540] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
System.Exception: Namespace and Folder name do not match. The top level namespace must match the folder name.
   at Terraria.ModLoader.Core.AssemblyManager.VerifyMod(String modName, Assembly assembly, Type& modType) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 214
   at Terraria.ModLoader.Core.AssemblyManager.Instantiate(ModLoadContext mod) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 187
   at Terraria.ModLoader.Core.AssemblyManager.<>c__DisplayClass11_0.<InstantiateMods>b__1(ModLoadContext mod) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 260
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Terraria.ModLoader.Core.AssemblyManager.InstantiateMods(List`1 modsToLoad, CancellationToken token) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 258
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 117
   at Terraria.ModLoader.ModLoader.<>c__DisplayClass48_0.<BeginLoad>b__0() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 104
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

[17:28:13.589] [.NET ThreadPool Worker/ERROR] [tML]: An error occurred while loading RedemptionAlpha v0.8
The mod(s) have been automatically disabled.
System.Exception: Namespace and Folder name do not match. The top level namespace must match the folder name.
   at Terraria.ModLoader.Core.AssemblyManager.VerifyMod(String modName, Assembly assembly, Type& modType) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 214
   at Terraria.ModLoader.Core.AssemblyManager.Instantiate(ModLoadContext mod) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 187
   at Terraria.ModLoader.Core.AssemblyManager.<>c__DisplayClass11_0.<InstantiateMods>b__1(ModLoadContext mod) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 260
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Terraria.ModLoader.Core.AssemblyManager.InstantiateMods(List`1 modsToLoad, CancellationToken token) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 258
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 117
[17:28:13.590] [.NET ThreadPool Worker/INFO] [tML]: Disabling Mod: RedemptionAlpha
[17:28:23.022] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = True): "tModLoader-Logs" 

```
![image](https://user-images.githubusercontent.com/35659194/190850653-7382c7a9-17e5-4d95-83ef-777549c50f0b.png)

**Comment by SnowyStarfall** [comment]
Rename the mod's folder in your Mod Sources to **Redemption** and recompile.

**Comment by miozus** [comment]
> Rename the mod's folder in your Mod Sources to **Redemption** and recompile.

Thank you! It works.
